config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    get 'orders/show'
  end
  devise_for :admins, skip: [:registrations, :passwords],controllers: {
    sessions: "admin/sessions"
  }

  devise_for :customers, skip: [:passwords],controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  scope module: :public do
    root to: 'homes#top'
    get 'homes/about' => 'homes#about', as: 'about'
    get 'customers/my_page' => 'customers#show', as: 'my_page'
    get 'customers/information/edit' => 'customers#edit', as: 'edit_information'
    patch 'customers/information/update' => 'customers#update', as: 'update_information'
    get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
    patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
    resources :addresses, only: [:new, :index, :edit, :create, :update, :destroy]
    resources :items, only: [:index, :show]
    delete 'cart_items/destroy_all' => 'cart_items#destroy_all', as: 'cart_items_destroy_all'
    resources :cart_items, only: [:new, :index, :update, :destroy, :create]
    post 'orders/confirm' => 'orders#confirm', as: 'confirm'
    get 'orders/complete' => 'orders#complete', as: 'complete'
    resources :orders, only: [:new, :index, :show, :create]
  end

  namespace :admin do
    root to: 'homes#top'
    resources :genres, only: [:index, :create, :edit, :update]
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :orders, only: [:show, :update] do
      resources :order_items, only: [:update]
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def get_image(size)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [50, 50]).processed
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * amount
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :addresses, dependent: :destroy
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

  def active_for_authentication?
    super && (self.is_deleted == false)
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :genre
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_one_attached :image
  def get_image(size)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [50, 50]).processed
  end

  def add_tax_price
    (self.price * 1.10).round
  end

  def with_tax_price
    (price * 1.1).floor
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { wait_payment: 0, payment_confirmation: 1, under_construction: 2, in_preparation: 3, already_sent: 4}
  belongs_to :customer
  has_many :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genres_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    genre = Genre.find(params[:id])
    genre.update(genres_params)
    redirect_to edit_admin_genre_path(genre.id)
  end

private
  def genres_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.page(params[:page]).per(10)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    item = Item.new(item_params)
    item.save
    redirect_to admin_item_path(item.id)
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item.id)
  end

  private

  def item_params
    params.require(:item).permit(:image, :genre_id, :name, :introduction, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  def show
    @order = Order.find(params[:id])
  end

  def update
    order = Order.find(params[:id])
    order.update(order_params)
    if order.status == "payment_confirmation"
      @order_items = order.order_items
      @order_items.each do |order_item|
      order_item.update(making_status: 2)
     end
    end
    # 1. 「注文ステータスが入金確認だったら」というif文
    # 2. 注文に紐づく、注文商品一覧を取得
    # 3. 注文商品一覧一つ一つのデータに対して、製作ステータスを「制作待ち」に更新する
    redirect_to admin_order_path(order.id)
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    admin_root_path
  end

  def after_sign_out_path_for(resource)
    admin_session_path
  end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :first_name_kana, :last_name_kana, :post_code, :address, :telephone_number, :email])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<main>
  <div class="container">
    <div class="col-md-3 my-4 text-center" style="background-color: #f0f0f0">
      <p>ジャンル編集</p>
    </div>
    <%= form_with model: @genre, url: admin_genre_path(@genre.id), method: :patch do |f| %>
    <div class="col-sm-5">
      <span class="genre font-size">ジャンル名　<%= f.text_field :name %>　<%= f.submit '変更を保存', class: "btn btn-success" %></span>
    </div>
  </div>
  <% end %>
</main>

app/views/admin/genres/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="col-md-3 my-4 text-center" style="background-color: #f0f0f0;">
      <p>ジャンル一覧・追加</p>
    </div>
<%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
  　<%= f.label :ジャンル名 %>
  　<%= f.text_field :name %>
  　<%= f.submit '新規登録', class: "btn btn-success" %>
<% end %>
  </div>
</div>


<div class="col-5">
  <table class="table mt-5">
    <thead>
      <tr>
        <th>ジャンル</th>
        <th></th>
      </tr>
    </thead>
    <% @genres.each do |genre| %>
    <tbody>
      <tr>
        <td>
          <%= genre.name %>
        </td>
        <td>
          <%= link_to "編集する", edit_admin_genre_path(genre.id), class: "btn btn-success"  %>
        </td>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

app/views/admin/items/edit.html.erb
<main>
  <div class="container">
    <div class="col-md-3">
      <p class="mt-4 text-center" style="background-color: #f0f0f0">商品編集</p>
    </div>
    <%= form_with model: @item,url: admin_item_path(@item.id), method: :patch do |f| %>
    <div class="col-md-6">
      <p class="font-5">商品画像　　　<%= f.file_field :image, placeholder: "プロフィール画像", accept: "image/*" %></p>
      <p class="font-5">商品名　　　　<%= f.text_field :name %></p>
      <p class="font-5">商品説明　　　<%= f.text_area :introduction %></p>
      <p class="font-5">ジャンル　　　<%= f.collection_select(:genre_id, Genre.all, :id, :name) %></p>
      <p class="font-5">税抜価格　　　<%= f.number_field :price %>円</p>
      <p class="font-5">
        販売ステータス
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, '販売中' %>
        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, '販売停止中' %>
      </p>
      <%= f.submit '変更を保存', class: "btn btn-success"  %>
    </div>
  </div>
  <% end %>
</main>

app/views/admin/items/index.html.erb
<main>
  <div class="container">
    <div class="row">
      <div class="col-md-3 my-4 text-center" style="background-color: #f0f0f0;">
        <p>商品一覧</p>
      </div>
      <div class="col-7"></div>
      <div class="col-2 mt-2">
        <%= link_to new_admin_item_path, method: :get do %>
          <i class="fa-regular fa-circle-plus fa-4x"></i>
        <% end %>
      </div>
    </div>
    <table class="table md-9">
      <tr>
        <th scope="col" style="width: 15%">商品ID</th>
        <th scope="col" style="width: 30%">商品名</th>
        <th scope="col" style="width: 10%">税抜価格</th>
        <th scope="col" style="width: 30%">ジャンル</th>
        <th scope="col" style="width: 15%">ステータス</th>
      </tr>
      <% @items.each do |item| %>
      <tbody>
        <tr>
          <td><%= item.id %></td>
          <td><%= link_to item.name, admin_item_path(item.id) %></td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td>
          <% if item.is_active %>
          <%= '販売中' %>
          <% else %>
          <%= '販売停止' %>
          <% end %>
          </td>
        </tr>
      </tbody>
      <% end %>
    </table>
    <%= paginate @items %>
  </div>
</main>

app/views/admin/items/new.html.erb
<main>
  <div class="container">
    <div class="col-md-3">
      <p class="mt-4 text-center" style="background-color: #f0f0f0">商品新規登録</p>
    </div>
    <%= form_with model: @item, url: admin_items_path do |f| %>
    <div class="col-md-5 text-left">
       <p class="font"> 商品画像　　　　<%= f.file_field :image, accept: "image/*" %></p>
       <p class="font">商品名　　　　<%= f.text_field :name %></p>
       <p class="font">商品説明　　　<%= f.text_area :introduction %></p>
       <p class="font"> ジャンル　　　<%= f.collection_select(:genre_id, Genre.all, :id, :name) %></p>
       <p class="font">税抜価格　　　<%= f.number_field :price %> 円</p>
       <p class="font">
         販売ステータス
        <%= f.label :is_active, '販売中' %>
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, '販売停止中' %>
        <%= f.radio_button :is_active, false %>
       </p>
       <span class="good"><%= f.submit '新規登録', class: "btn btn-success" %></span>
    </div>
  </div>
</main>
<% end %>

app/views/admin/items/show.html.erb
<main>
  <div class="container">
    <div class="col-md-3">
      <p class="mt-4 text-center" style="background-color: #f0f0f0">商品詳細</p>
    </div>
    <div class="row">
      <div class="col-md-4">
        <%= image_tag @item.image, size: "200x200" %>
      </div>
      <div class="col-md-8">
        <p class="font-2">商品名　　　　<%= @item.name %></p>
        <p class="font-2">商品説明　　　<%= @item.introduction %></p>
        <p class="font-2">ジャンル　　　<%= @item.genre.name %></p>
        <p class="font-2">
          税込価格　　　　<%= @item.add_tax_price.to_s(:dalimited) %>円<br>
          (税抜価格)　　　(<%= @item.price %>)円
        </p>
        <p class="status">
          販売ステータス
        　<% if @item.is_active %>
          販売中
          <% else %>
          販売停止中
          <% end %>
        </p>
        <%= link_to "編集する", edit_admin_item_path(@item.id), class: "btn btn-success" %>
      </div>
    </div>
  </div>
</main>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <table class="table">
        <thead>
          <tr>
            <th scope="col" style="width: 30%">購入者</th>
            <th scope="col" style="width: 70%"><%= @order.name %></th>
          </tr>
          <tr>
            <th scope="col" style="width: 30%">注文日</th>
            <th scope="col" style="width: 70%"><%= @order.created_at.strftime('%Y/%m/%d') %></th>
          </tr>
          <tr>
            <th scope="col" style="width: 30%">配送先</th>
            <th scope="col" style="width: 70%">〒<%= @order.postal_code %>　<%= @order.address %><br><%= @order.name %></th>
          </tr>
          <tr>
            <th scope="col" style="width: 30%">支払方法</th>
            <th scope="col" style="width: 70%"><%= @order.payment_method_i18n %></th>
          </tr>
          <tr>
            <%= form_with model: @order, url: admin_order_path(@order.id), method: :patch do |f| %>
            <th scope="col" style="width: 30%">注文ステータス</th>
            <th scope="col" style="width: 70%"><%= f.select :status, [['入金待ち',"wait_payment"], ['入金確認',"payment_confirmation"], ['製作中',"under_construction"], ['発送準備中',"in_preparation"],['発送済み',"already_sent"]] %>　　<%= f.submit '更新', class: "btn btn-success" %></th>
            <% end %>
          </tr>
        </thead>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-8">
      <table class="table">
        <thead>
          <tr>
            <th scope="col" style="width: 30%">商品名</th>
            <th scope="col" style="width: 15%">単価(税込)</th>
            <th scope="col" style="width: 10%">数量</th>
            <th scope="col" style="width: 15%">小計</th>
            <th scope="col" style="width: 30%">制作ステータス</th>
          </tr>
        </thead>
        <% @order.order_items.each do |order_item| %>
        <tbody>
          <tr>
            <td><%= order_item.item.name %></td>
            <td><%= order_item.item.add_tax_price %></td>
            <td><%= order_item.amount %></td>
            <td><%= order_item.item.add_tax_price * order_item.amount %></td>
            <%= form_with model: [@order, order_item], url: admin_order_order_item_path(@order.id, order_item.id), method: :patch do |f| %>
            <td><%= f.select :making_status, [['着手不可',1], ['製作待ち',2], ['製作中',3], ['製作完了',4]] %>　　<%= f.submit '更新', class: "btn btn-success" %></td>
            <% end %>
          </tr>
        </tbody>
        <% end %>
      </table>
    </div>
    <div class="col-1"></div>
    <div class="col-3">
      <span class="money">
        <p class="items">商品合計　　　　<%= (@order.total_payment) - (@order.shoping_cost) %></p>
      </span>
      <span class="money">
        <p class="items">送料　　　　　　<%= @order.shoping_cost %></p>
      </span>
      <span class="money">
        <p class="items">請求金額合計　　<%= @order.total_payment %></p>
      </span>
    </div>

  </div>
</div>